WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using DomainClasses.Entities;
using System.Linq.Dynamic;
using System.Net.Http;
using System.Threading.Tasks;
using DNTBreadCrumb;
using Newtonsoft.Json;

//Import the Dynamic LINQ library

namespace WebApp.Controllers
{
    public class CarsRESTService
    {
        readonly string baseUri = "http://api.csspro.ir/api/organization/";

        public List<Organization> GetCars()
        {
            string uri = baseUri;
            using (HttpClient httpClient = new HttpClient())
            {
                Task<String> response = httpClient.GetStringAsync(uri);
                return JsonConvert.DeserializeObjectAsync<List<Organization>>(response.Result).Result;
            }
        }
    }
    [BreadCrumb(Title = "واحدها", UseDefaultRouteUrl = true, RemoveAllDefaultRouteValues = true,
        Order = 0, GlyphIcon = "fa fa-link")]
    public class UnitsController : Controller
    {
        private static CarsRESTService carsService = new CarsRESTService();
        // GET: Units
        [BreadCrumb(Title = "لیست واحدها", Order = 1)]
        public ActionResult Index()
        {
            List<Organization> org = carsService.GetCars().ToList();
            return View(org);
        }

        [HttpGet]
        [BreadCrumb(Title = "افزودن واحده جدید", Order = 2)]
        public ActionResult AddOrg()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Addorg(Organization organization)
        {


            return RedirectToAction("AddOrg");
        }
      
    }
}

WebApp/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

WebApp/Views/Shared/_BreadCrumb.cshtml
@using DNTBreadCrumb
@{
    var homeUrl = Url.Action("Index", "Home");
    const string homePage = "داشبورد";

    var breadCrumbs = this.Context.Items[BreadCrumbExtentions.CurrentBreadCrumbKey] as List<BreadCrumb>;
    var currentFullUrl = this.Request.Url.ToString();
    var currentRouteUrl = Url.RouteUrl(this.ViewContext.RouteData.Values);
    var isCurrentPageHomeUrl = homeUrl.Equals(currentFullUrl, StringComparison.OrdinalIgnoreCase) ||
                               homeUrl.Equals(currentRouteUrl, StringComparison.OrdinalIgnoreCase);
}

@if (breadCrumbs != null && breadCrumbs.Any())
{
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    @if (isCurrentPageHomeUrl)
                    {
                        <li class="active">
                            <span class="fa fa-home" aria-hidden="true"></span>
                            @homePage
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@homeUrl">
                                <span class="fa fa-home" aria-hidden="true"></span>
                                @homePage
                            </a>
                        </li>
                    }

                    @foreach (var node in breadCrumbs.OrderBy(x => x.Order))
                    {
                        if (node.Url.Equals(homeUrl, StringComparison.OrdinalIgnoreCase))
                        {
                            continue;
                        }

                        if (node.Url.Equals(currentFullUrl, StringComparison.OrdinalIgnoreCase) ||
                            node.Url.Equals(currentRouteUrl, StringComparison.OrdinalIgnoreCase))
                        {
                            <li class="active">
                                @if (!string.IsNullOrWhiteSpace(node.GlyphIcon))
                                {
                                    <span class="@node.GlyphIcon" aria-hidden="true"></span>
                                }
                                @node.Title
                            </li>
                        }
                        else
                        {
                            <li>
                                <a href="@node.Url">
                                    @if (!string.IsNullOrWhiteSpace(node.GlyphIcon))
                                    {
                                        <span class="@node.GlyphIcon" aria-hidden="true"></span>
                                    }
                                    @node.Title
                                </a>
                            </li>
                        }
                    }
                </ol>
            </div>
        </div>
    </div>
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>N-Tire Application</title>
    <link rel="icon" type="image/ico" href="#" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ============ Stylesheets ============= -->
    <link href="~/assets/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <link href="~/assets/css/CssFramework.css" rel="stylesheet" />
    <link href="~/assets/css/Main.css" rel="stylesheet"/>
    
</head>
<body>
    <!-- ======Heder ====== -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a href="#menu-toggle" class="fa fa-bars fa-2x pull-right" id="menu-toggle"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav"></ul>

            <ul class="nav navbar-nav navbar-left">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i> کاربر سایت <span class="caret"></span>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-user pull-left"></i>پروفایل</a></li>
                        <li><a href="#"><i class="fa fa-cog pull-left"></i>تنظیمات</a></li>
                        <li><a href="#"><i class="fa fa-lock pull-left"></i>تغییر رمز عبور</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#"><i class="fa fa-sign-out pull-left"></i>خروج</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-left">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="badge alertbadge bg-lightred">5</span><i class="fa fa-bell"></i> <span class="caret"></span>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">آمارهای رسیده</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">واحد شماره یک</a></li>
                        <li><a href="#">واحد شماره دو</a></li>
                        
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-left">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="badge alertbadge bg-lightred">3</span><i class="fa fa-envelope"></i> <span class="caret"></span>

                    </a>

                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group ">
                    <input type="text" class="form-control" placeholder="به دنبال ماژولی هستید؟">
                </div>
                <button type="submit" class="btn btn-default">جستجو</button>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

    <!--Side Bar start-->
    <div id="wrapper">
        <div class="col-md-4">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#">
                            SM CMS
                        </a>
                    </li>
                    <li>
                        <a href="/admin/index"><i class="fa fa-home"></i>&nbsp;داشبورد </a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-envelope"></i>&nbsp;ایمیل ها</a>
                        <ul class="submenu">
                            <li><a href="#"><i class="fa fa-reply"></i>&nbsp;رسیده ها</a></li>
                            <li><a href="#"><i class="fa fa-send"></i>&nbsp;ارسال شده ها</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i>&nbsp;رسیده ها</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="/units/index"><i class="fa fa-cogs"></i>&nbsp;واحد ها</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bolt"></i>&nbsp;رویدادهای سیستم</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-image"></i>&nbsp;اسلایدرها</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-users"></i>&nbsp;کاربران</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-user-secret"></i>&nbsp;نقش های امنیتی</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->

        <div id="page-content-wrapper">
            @{Html.RenderPartial("_BreadCrumb");}
            @*<ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">داشبورد</a></li>
                <li class="breadcrumb-item active">درباره ما</li>
            </ol>*@
            
            @RenderBody()




        </div>
        <!-- /#page-content-wrapper -->

    </div>


    <!--SideBar End-->





    <!-- =============== Scripts ================= -->
    <script src="/assets/Scripts/JQuery/jquery-1.9.1.min.js"></script>
    <!--For debug mode-->
    <script src="/assets/Scripts/JQuery/jquery-1.9.1.intellisense.js"></script>
   <script src="/assets/Scripts/bootstrap/bootstrap.min.js"></script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Units/AddOrg.cshtml
@{
    ViewBag.Title = "AddOrg";
}


@using (Html.BeginForm("AddOrg", "Units", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="panel panel-default">

        <div class="panel-heading">
            <span><i class="fa fa-edit"></i>افزودن واحد جدید</span>

        </div>
        <div class="panel-body">
            <div class="form-group">
                <label for="Name">نام واحد</label>
                <input type="text" class="form-control" name="Name" id="Name">
                <label for="Desc">توضیحات</label>
                <input type="text" class="form-control" name="Desc" id="Desc">

            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i>&nbsp;ثبت اطلاعات</button>
           <a href="@Url.Action("Index", "Units")" class="btn btn-warning"><i class="fa fa-arrow-right"></i>&nbsp;بازگشت به لیست واحد ها</a>
        </div>


    </div>
}

WebApp/Views/Units/Index.cshtml
@model IEnumerable<DomainClasses.Entities.Organization>
@{
    ViewBag.Title = "Index";
}
<div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    لیست واحد های ثبت شده در سیستم
</div>


<div class="table-responsive">
    <table class="table table-hover table-bordered">
        <caption><a href="@Url.Action("AddOrg","Units")" class="btn btn-success pull-right mb-10"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;افزودن واحد جدید</a></caption>
        <thead>
        
        <tr>
            <th>#</th>
            <th>نام واحد</th>
            <th> توضیحات</th>
            <th>اختیارات</th>

        </tr>
        </thead>
        <tbody>

        @{
            foreach (var Organization in Model)
            {

                <tr>
                    <td>@Organization.Id</td>
                    <td>@Organization.Name</td>
                    <td>@Organization.Desc</td>
                    <td><a class="btn btn-success"><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;مشاهده سوابق</a>&nbsp;<a class="btn btn-warning"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;ویرایش</a>&nbsp;<a class="btn btn-danger"><i class="fa fa-remove" aria-hidden="true"></i>&nbsp;حذف</a></td>
                </tr>

            }

        }

        </tbody>
    </table>

</div>